- .github/dependabot.yml
- .github/workflows/daily_security.yml
>  Dependabot ignore kube-*, check github-actions, daily security run

- .github/dependabot.yml
- .github/pull_request_template.md
- .github/workflows/rust.yml
- CHANGELOG.md
- Cargo.lock
- crd/Cargo.toml
- deny.toml
- operator/Cargo.toml
- server/Cargo.toml
This PR is part of a chain of PRs across all our projects to make them as consistent as possible in preparation for our first release.
Things it can contain (not all might be applicable to all repositories):
- Cargo.toml
- Add `repository` key
- Set version properly
- Sort keys
- deny.toml consistency
- Pull request template
- Github CI consistency (e.g. rustdoc)
- cargo update
- Dependabot does not ignore stackable components anymore
- Adds changelog & readme
> Project updates

- Cargo.lock
- crd/Cargo.toml
- operator/Cargo.toml
- server/Cargo.toml
> Switched to tags.

- CHANGELOG.md
- Cargo.lock
- rust/crd/Cargo.toml
- rust/operator-binary/Cargo.toml
- rust/operator/Cargo.toml
Release 0.2.1. DO NOT SQUASH MERGE!
> Release 0.2.1

- CHANGELOG.md
- Cargo.lock
- deploy/crd/kafkacluster.crd.yaml
- rust/crd/Cargo.toml
- rust/crd/src/error.rs
- rust/crd/src/lib.rs
- rust/operator-binary/Cargo.toml
- rust/operator-binary/src/stackable-kafka-operator.rs
- rust/operator/Cargo.toml
- rust/operator/src/lib.rs
Adapted to operator-rs tag 0.2.2
Adapted to zookeeper tag 0.4.0
Adapted to opa tag 0.4.0
Added ProductVersion and Conditions to status.
Added up and downgrade ability.
> Implemented versioning from operator-rs

- CHANGELOG.md
- Cargo.lock
- deploy/crd/kafkacluster.crd.yaml
- rust/crd/Cargo.toml
- rust/crd/src/lib.rs
- rust/operator-binary/Cargo.toml
- rust/operator/Cargo.toml
- rust/operator/src/lib.rs
Draft because it doesn't build yet due to transitive version conflicts.
Fixes #180
> Use sticky scheduler.

- examples/simple-kafkacluster.yaml
> Adapted example version 2.8.0 -> 2.8.1

- deploy/helm/kafka-operator/configs/properties.yaml
- deploy/helm/kafka-operator/crds/crds.yaml
- deploy/manifests/configmap.yaml
- deploy/manifests/crds.yaml
Seems like whatever automation we have to do this didn't actually seem to run?
> make compile-chart

- Cargo.lock
- README.adoc
- README.md
- rust/crd/Cargo.toml
- rust/operator/src/kafka_controller.rs
- README update
- Dependency updates
- Remove unused dependencies
- Rustdoc fixes
> Various changes

- deploy/helm/kafka-operator/configs/properties.yaml
- deploy/manifests/configmap.yaml
The last PR contained changes to the product config file, which for some reason were not reflected in the Helm chart and Kustomize manifests.
Since all of this will be overhauled as part of https://github.com/stackabletech/issues/issues/156 I don't want to waste time investigating what went wrong and just want the right stuff published.
> Fix product-config in Helm chart & Kustomize manifest

- CHANGELOG.md
- deploy/helm/kafka-operator/crds/crds.yaml
- rust/crd/src/lib.rs
cherry picked from commit 6065e7976758c6b7a6e864985667b68525f1f7ed
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Add missing crd defaults to 23.4

- Cargo.lock
- Cargo.toml
- deploy/helm/kafka-operator/crds/crds.yaml
- rust/crd/Cargo.toml
- rust/operator-binary/Cargo.toml
- rust/operator/Cargo.toml
- tests/templates/kuttl/upgrade/04-assert.yaml.j2
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Switch to workspace dependencies

- CHANGELOG.md
- deploy/config-spec/properties.yaml
- deploy/helm/kafka-operator/configs/properties.yaml
- docs/modules/kafka/pages/usage-guide/configuration-environment-overrides.adoc
- rust/crd/src/lib.rs
- rust/crd/src/security.rs
- rust/operator/src/kafka_controller.rs
CI: https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/kafka-operator-it-custom/47/
Use JVM defaults.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> JVM config overrides

- docs/modules/kafka/pages/getting_started/installation.adoc
- docs/modules/kafka/pages/index.adoc
- docs/modules/kafka/pages/usage-guide/security.adoc
Part of https://github.com/stackabletech/stackable-cockpit/pull/101
> docs: Update references

- rust/operator/src/kafka_controller.rs
- rust/operator/src/pod_svc_controller.rs
Part of https://github.com/stackabletech/operator-rs/issues/649
> refactor: Use operator-rs Duration

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- deploy/helm/kafka-operator/crds/crds.yaml
- docs/modules/kafka/examples/getting_started/kafka.yaml
- docs/modules/kafka/examples/getting_started/zookeeper.yaml
- docs/modules/kafka/partials/supported-versions.adoc
- examples/logging/simple-kafka-cluster-opa-log4j.yaml
- examples/opa/simple-kafka-cluster-opa-allow-all.yaml
- examples/tls/simple-kafka-cluster-tls.yaml
- rust/operator/src/kafka_controller.rs
- rust/operator/src/pod_svc_controller.rs
- tests/templates/kuttl/logging/01-install-kafka-vector-aggregator.yaml
- tests/templates/kuttl/tls/20-install-kafka.yaml.j2
- tests/templates/kuttl/tls/30-assert.yaml.j2
- tests/templates/kuttl/tls/30-prepare-test-kafka.yaml.j2
- tests/templates/kuttl/tls/test_client_auth_tls.sh
- tests/templates/kuttl/tls/test_client_tls.sh
- tests/test-definition.yaml
- added support for versions 3.4.1, 3.5.0
- removed support for versions 2.7.1, 3.1.0, 3.2.0, 3.3.1
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> New version 3.4.1, 3.5.0

- CHANGELOG.md
- docs/modules/kafka/pages/usage-guide/operations/znode-id.adoc
- docs/modules/kafka/partials/nav.adoc
Fixes https://github.com/stackabletech/kafka-operator/issues/626.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Docs: internal clusterId check

- Cargo.lock
- Cargo.toml
- rust/operator/Cargo.toml
- rust/operator/src/kafka_controller.rs
- rust/operator/src/lib.rs
Part of https://github.com/stackabletech/product-config/issues/95
> refactor: Use updated product-config

- tests/templates/kuttl/cluster-operation/10-install-zk.yaml.j2
- tests/templates/kuttl/configuration/10-install-zk.yaml.j2
- tests/templates/kuttl/delete-rolegroup/01-install-zk.yaml.j2
- tests/templates/kuttl/logging/02-install-zookeeper.yaml.j2
- tests/templates/kuttl/smoke/20-install-zk.yaml.j2
- tests/templates/kuttl/tls/10-install-zookeeper.yaml.j2
- tests/templates/kuttl/upgrade/01-install-zk.yaml.j2
based on https://github.com/stackabletech/zookeeper-operator/pull/739
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Updated integration tests for ZooKeeper CRD change

- docs/modules/kafka/examples/getting_started/getting_started.sh
- docs/modules/kafka/examples/getting_started/getting_started.sh.j2
- docs/modules/kafka/examples/getting_started/install-operator-output.txt
- docs/modules/kafka/examples/getting_started/install-operator-output.txt.j2
- docs/modules/kafka/pages/getting_started/installation.adoc
- docs/templating_vars.yaml
The listener-operator is now one of the fundamental operators, along with the commons- and secret-operators, and should be mentioned accordingly everywhere.
```[tasklist]
```
```[tasklist]
```
> docs: Add listener-operator where missing

- CHANGELOG.md
- deploy/helm/kafka-operator/templates/_helpers.tpl
- deploy/helm/kafka-operator/templates/deployment.yaml
- deploy/helm/kafka-operator/templates/roles.yaml
- deploy/helm/kafka-operator/values.yaml
Part of: https://github.com/stackabletech/issues/issues/501
> feat(helm): support labels in values.yaml

- deploy/helm/kafka-operator/values.yaml
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Add Stackable vendor label to default values.yaml

- docs/modules/kafka/pages/index.adoc
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> docs: update supported versions text and other minor improvements

- docs/modules/kafka/pages/usage-guide/logging.adoc
- docs/modules/kafka/pages/usage-guide/monitoring.adoc
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> docs: fix links

- CHANGELOG.md
- docs/modules/kafka/examples/getting_started/kafka.yaml
- docs/modules/kafka/pages/usage-guide/security.adoc
- docs/modules/kafka/partials/supported-versions.adoc
- examples/logging/simple-kafka-cluster-opa-log4j.yaml
- examples/opa/simple-kafka-cluster-opa-allow-all.yaml
- examples/tls/simple-kafka-cluster-tls.yaml
- rust/crd/src/affinity.rs
- rust/crd/src/lib.rs
- rust/crd/src/listener.rs
- tests/test-definition.yaml
Integration test was successful: https://ci.stackable.tech/view/06%20Replicated/job/kafka-operator-it-replicated/3/console
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> chore: Add versions 3.7.1 and 3.6.2

- tests/templates/kuttl/logging/01-install-kafka-vector-aggregator.yaml
Use Vector Helm chart version 0.34.0 (Vector 0.39.0) in the logging test
https://github.com/vectordotdev/helm-charts/blob/vector-0.34.0/CHANGELOG.md#vector-0340---2024-06-17
Implements stackabletech/docker-images#561
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Use Vector Helm chart version 0.34.0 in the logging test

- docs/modules/kafka/examples/getting_started/zookeeper.yaml
Part of https://github.com/stackabletech/issues/issues/613
> fix: Adjust getting-started script for release 24.7.0

- docs/modules/kafka/examples/getting_started/zookeeper.yaml
> fix: Adjust getting-started script for release 24.7.

- tests/templates/kuttl/logging/01-install-kafka-vector-aggregator.yaml
Part of https://github.com/stackabletech/issues/issues/626
```[tasklist]
```
> chore: Bump Vector to 0.40.0

- deploy/helm/kafka-operator/templates/roles.yaml
See: https://github.com/stackabletech/issues/issues/624
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> fix(helm): use same scc as olm

- Cargo.lock
- Cargo.nix
- Cargo.toml
- crate-hashes.json
- tests/templates/kuttl/smoke/30-install-kafka.yaml.j2
- tests/templates/kuttl/smoke/31-assert.yaml
Part of: https://github.com/stackabletech/issues/issues/548
:green_circle: Test:
```
$ ./scripts/run-tests --test-suite smoke-latest
...
--- PASS: kuttl (47.22s)
--- PASS: kuttl/harness/smoke_kafka-3.7.1_zookeeper-3.9.2_use-client-tls-false_openshift-false (46.57s)
PASS
➜
```
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> fix(test): smoke testing env and config overrides

- tests/templates/kuttl/logging/01-install-kafka-vector-aggregator.yaml
Upgrade the Vector aggregator in the logging tests
The Helm chart version 0.36.1 deploys Vector 0.41.1.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> chore: Upgrade the Vector aggregator in the logging tests

- Cargo.lock
- Cargo.toml
- deploy/helm/kafka-operator/crds/crds.yaml
- rust/operator-binary/src/kafka_controller.rs
part of: https://github.com/stackabletech/issues/issues/640
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> chore: bump op-rs

- Cargo.lock
- Cargo.toml
- rust/crd/src/security.rs
- rust/operator-binary/src/kafka_controller.rs
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> chore: Bump to operator-rs 0.78.0

- docs/modules/kafka/examples/getting_started/getting_started.sh
- docs/modules/kafka/examples/getting_started/install_output.txt
Part of https://github.com/stackabletech/issues/issues/647.
> docs: Update release in getting_started

- CHANGELOG.md
- Cargo.lock
- rust/crd/src/security.rs
- rust/operator-binary/src/kafka_controller.rs
- tests/templates/kuttl/smoke/30-assert.yaml.j2
- tests/templates/kuttl/smoke/32-assert.yaml
Part of https://github.com/stackabletech/issues/issues/527
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> feat: run containerdebug in the background

- CHANGELOG.md
- Cargo.lock
- Cargo.nix
- Cargo.toml
- crate-hashes.json
- deploy/helm/kafka-operator/templates/roles.yaml
- rust/crd/src/lib.rs
- rust/operator-binary/Cargo.toml
- rust/operator-binary/src/discovery.rs
- rust/operator-binary/src/kafka_controller.rs
- rust/operator-binary/src/main.rs
Part of https://github.com/stackabletech/operator-rs/issues/942
```[tasklist]
```
> chore: Update to operator-rs 0.84.0

- tests/templates/kuttl/logging/01-install-kafka-vector-aggregator.yaml
Part of https://github.com/stackabletech/docker-images/issues/967
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> chore: Update Vector to 0.43.1 in integration tests

- examples/logging/simple-kafka-cluster-opa-log4j.yaml
- examples/opa/simple-kafka-cluster-opa-allow-all.yaml
Part of: https://github.com/stackabletech/docker-images/issues/969
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> chore(opa) bump to 1.0.0 in docs

- CHANGELOG.md
- Cargo.lock
- Cargo.nix
- Cargo.toml
- crate-hashes.json
- deploy/helm/kafka-operator/crds/crds.yaml
- deploy/helm/kafka-operator/values.yaml
- docs/modules/kafka/pages/reference/environment-variables.adoc
- tests/templates/kuttl/kerberos/01-install-krb5-kdc.yaml.j2
- tests/templates/kuttl/kerberos/30-access-kafka.txt.j2
- tests/templates/kuttl/logging/05-install-kafka-test-runner.yaml
- tests/templates/kuttl/smoke/40-install-test-container.yaml
- tests/templates/kuttl/upgrade/03-write-data.yaml.j2
- tests/templates/kuttl/upgrade/05-read-data.yaml.j2
- tests/test-definition.yaml
Openshift tests:
```
--- PASS: kuttl (357.93s)
--- PASS: kuttl/harness/cluster-operation_kafka-latest-3.7.1_zookeeper-latest-3.9.2_openshift-true (113.75s)
--- PASS: kuttl/harness/tls_kafka-3.8.0_zookeeper-latest-3.9.2_use-client-tls-true_use-client-auth-tls-true_openshift-true (170.71s)
--- PASS: kuttl/harness/kerberos_kafka-3.8.0_zookeeper-latest-3.9.2_openshift-true_krb5-1.21.1_kerberos-realm-PROD.MYCORP_kerberos-backend-mit (70.28s)
--- PASS: kuttl/harness/configuration_kafka-latest-3.7.1_zookeeper-latest-3.9.2_openshift-true (26.78s)
--- PASS: kuttl/harness/delete-rolegroup_kafka-3.8.0_zookeeper-latest-3.9.2_openshift-true (53.44s)
--- PASS: kuttl/harness/smoke_kafka-3.8.0_zookeeper-3.9.2_use-client-tls-true_openshift-true (75.12s)
--- PASS: …
```
> chore: add oci references, merge templating changes

- tests/test-definition.yaml
Part of https://github.com/stackabletech/docker-images/issues/968.
This PR corrects work done in https://github.com/stackabletech/kafka-operator/pull/822.
> test: Correct the versions to test against

- CHANGELOG.md
- docs/modules/kafka/partials/supported-versions.adoc
This was accidentally missed in https://github.com/stackabletech/kafka-operator/pull/834.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> docs: Update supported versions

- docs/modules/kafka/examples/getting_started/zookeeper.yaml
- tests/test-definition.yaml
Part of https://github.com/stackabletech/docker-images/issues/1020
> chore: Update ZooKeeper to 3.9.3 pre-25.3.0

- tests/templates/kuttl/logging/01-install-kafka-vector-aggregator.yaml
Part of: https://github.com/stackabletech/docker-images/issues/1146
> chore: bump vector chart to 0.43.0

- CHANGELOG.md
- Cargo.lock
- Cargo.nix
- Cargo.toml
- deploy/helm/kafka-operator/Chart.yaml
- deploy/helm/kafka-operator/crds/crds.yaml
- docs/antora.yml
- docs/modules/kafka/examples/getting_started/getting_started.sh
- docs/modules/kafka/examples/getting_started/install_output.txt
- docs/templating_vars.yaml
- tests/release.yaml
- tests/templates/kuttl/upgrade/04-assert.yaml.j2
> [!CAUTION]
> ## DO NOT MERGE MANUALLY!
> This branch will be merged (and the commit tagged) by stackable-utils once any necessary commits have been cherry-picked to here from the main branch.
> chore: Release 25.7.0-rc1

- CHANGELOG.md
- deploy/helm/kafka-operator/templates/roles.yaml
> fix: Backport Add RBAC permission to patch events

- CHANGELOG.md
- Cargo.lock
- Cargo.nix
- Cargo.toml
- deploy/helm/kafka-operator/Chart.yaml
- docs/modules/kafka/examples/getting_started/getting_started.sh
- docs/modules/kafka/examples/getting_started/install_output.txt
- docs/templating_vars.yaml
- tests/release.yaml
- tests/templates/kuttl/upgrade/04-assert.yaml.j2
> [!CAUTION]
> ## DO NOT MERGE MANUALLY!
> This branch will be merged (and the commit tagged) by stackable-utils once any necessary commits have been cherry-picked to here from the main branch.
> chore: Release 25.7.0

- tests/templates/kuttl/logging/01-install-kafka-vector-aggregator.yaml
Part of https://github.com/stackabletech/docker-images/issues/1233
```
--- FAIL: kuttl (572.07s)
--- FAIL: kuttl/harness (0.00s)
--- PASS: kuttl/harness/logging_kafka-3.9.1_zookeeper-latest-3.9.3_openshift-false (270.79s)
--- FAIL: kuttl/harness/logging_kafka-3.7.2_zookeeper-latest-3.9.3_openshift-false (341.03s)
--- PASS: kuttl/harness/logging_kafka-3.9.0_zookeeper-latest-3.9.3_openshift-false (301.27s)
FAIL
```
The failed test succeeded but timed out on namespace deletion.
> chore: Bump vector version for 25.11.0
