- crd/src/main.rs
- operator/src/lib.rs
Previously this operator used custom labels defined only by this operator to track role_group, node_type and cluster name.
This PR changes this behavior to instead use the best practice labels as recommended by Kubernetes [1].
These labels are defined in the operator framework.
The PR assigns these as follows:
```
app.kubernetes.io/instance -> for the name of the service the pod belongs to (owner of the pod)
app.kubernetes.io/version -> for the deployed kafka version
app.kubernetes.io/component -> for the node type, i.e. "broker" at the moment
app.kubernetes.io/role-group -> for the groups defined in inventory
```
[1] https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/
> Moved to using labels defined in operator-rs

- Cargo.lock
- crd/Cargo.toml
- operator/Cargo.toml
- operator/src/lib.rs
- server/src/main.rs
This updates the dependency on operator-rs to include the update to kube-rs 0.52.
Additionally, finalizer handling is re-introduced in this PR, which was made optional in the framework a while ago.
Upon deletion the operator removes all pods and stops processing.
> Updated operator-rs dependency and introduced finalizer handling

- crd/src/lib.rs
- operator/src/lib.rs
The serde variant enclosed the version string in "" (correctly so) - which is not allowed as label content in K8s, since it does not start and end with an alphanumeric character.
> Change serialization for KafkaVersion enum to use strum instead of serde_json

- .github/workflows/daily_security.yml
- .github/workflows/nightly.yml
- .github/workflows/rust.yml
This gathers all the current dependabot upgrade PRs into one to cut down on noise.
fixes #87 
fixes #86 
fixes #85 
fixes #84 
fixes #83
> Merge dependabot action versioning PRs into one

- Cargo.lock
- crd/Cargo.toml
- crd/kafkaclusters.crd.yaml
- crd/src/lib.rs
- examples/simple-kafkacluster.yaml
- operator/src/lib.rs
Changes internal representation of Kafka version to a struct instead of an enum.
This version representation also includes the scala version that Kafka was compiled for, which was hard coded before.
Removes hard coded Kafka version in container command.
fixes #75
fixes #78
fixes #79
> Changes internal representation of Kafka version and include Scala version 

- operator/src/lib.rs
In order to avoid naming collisions of pods this PR adds the name of the node that a pod is scheduled on to the pod name.
This will not help once we start supporting multiple pods on the same node, but there are plans to use `generateName` instead of `Name` - this would provide unique hashes as part of the names.
Another factor to consider is that this method only works as long as the operator schedules pods itself, instead of relying on the pod scheduler from Kubernetes.
> Add name of node that a pod is scheduled on to the podname

- Cargo.lock
- operator/Cargo.toml
This makes the following dependabot PR obsolete: https://github.com/stackabletech/kafka-operator/pull/105
It is a `bugfix` because the previous version of handlebars was _3_ instead of _3.0_.
> Update handlebars version to 4.0

- .github/workflows/rust.yml
- deny.toml
Currently we run cargo-audit on pull requests as well as once per day. 
This only checks for security advisories, but we'd also like to ensure that all our dependencies are licensed under compatible licenses, so we added a cargo deny check on pull request. This also scans for security advisories, so we can remove the audit action on PRs. But we will keep in daily, because this action opens issues on the repository, which is nice.
> Switched cargo-audit action on PR to cargo deny which includes license scans

- deploy/config-spec/properties.yaml
- rust/operator/src/kafka_controller.rs
The default logs.dir for Kafka is moved to a subdirectory of the volume mount, as Kafka is troubled by the presence of the "lost+found" folder which resides in the root dir.
Added an init container to chown the data directory to the Stackable user.
fixes #279
> Fix issues on GKE

- CHANGELOG.md
- tests/templates/kuttl/upgrade/04-upgrade-kafka.yaml.j2
Part of https://github.com/stackabletech/issues/issues/404
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> test: Fix upgrade test

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- rust/crd/src/lib.rs
- rust/crd/src/security.rs
- rust/operator/src/kafka_controller.rs
- rust/operator/src/product_logging.rs
- tests/templates/kuttl/logging/kafka-vector-aggregator-values.yaml.j2
- tests/templates/kuttl/tls/test_client_auth_tls.sh
- tests/templates/kuttl/tls/test_client_tls.sh
- removed copying of keystores, now accessed directly vom secret-op moints (nothing is added)
- do not import system trust store anymore
- removed prepare container
fixes https://github.com/stackabletech/kafka-operator/issues/618
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Let secret op create pkcs12 stores

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- deploy/helm/kafka-operator/crds/crds.yaml
- docs/modules/kafka/pages/usage-guide/operations/graceful-shutdown.adoc
- rust/crd/Cargo.toml
- rust/crd/src/lib.rs
- rust/crd/src/security.rs
- rust/operator/Cargo.toml
- rust/operator/src/kafka_controller.rs
- rust/operator/src/operations/graceful_shutdown.rs
- rust/operator/src/operations/mod.rs
- rust/operator/src/product_logging.rs
- tests/templates/kuttl/smoke/30-assert.yaml.j2
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> feat: Support graceful shutdown

- docs/modules/kafka/pages/usage-guide/operations/graceful-shutdown.adoc
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> docs: Fix antora link

- tests/templates/kuttl/smoke/30-assert.yaml.j2
Not all storage providers honor the storage request sizes.
> Do not test for storage status

- CHANGELOG.md
- docs/modules/kafka/examples/getting_started/kafka.yaml
- docs/modules/kafka/pages/usage-guide/security.adoc
- docs/modules/kafka/partials/supported-versions.adoc
- examples/logging/simple-kafka-cluster-opa-log4j.yaml
- examples/opa/simple-kafka-cluster-opa-allow-all.yaml
- examples/tls/simple-kafka-cluster-tls.yaml
- rust/crd/src/affinity.rs
- rust/crd/src/lib.rs
- rust/crd/src/listener.rs
- tests/test-definition.yaml
- add version `3.5.2`, `3.6.1`
- remove kafka version `2.8.2` `3.4.0`, `3.5.1`
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Add support for version 3.5.2, 3.6.1

- tests/templates/kuttl/upgrade/03-write-data.yaml.j2
- tests/templates/kuttl/upgrade/05-read-data.yaml.j2
- tests/test-definition.yaml
After switching to stand-alone `kcat`, the upgrade test finally succeeded on OpenShift 4.15
```
--- PASS: kuttl (104.91s)
--- PASS: kuttl/harness/upgrade_zookeeper-3.8.3_upgrade_old-3.5.2_upgrade_new-3.6.1_use-client-tls-true_use-client-auth-tls-true_openshift-true (104.67s)
```
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> fix(tests): openshift tweaks

- tests/release.yaml
- tests/templates/kuttl/cluster-operation/00-patch-ns.yaml.j2
- tests/templates/kuttl/configuration/00-patch-ns.yaml.j2
- tests/templates/kuttl/delete-rolegroup/00-patch-ns.yaml.j2
- tests/templates/kuttl/logging/00-patch-ns.yaml.j2
- tests/templates/kuttl/smoke/00-patch-ns.yaml.j2
- tests/templates/kuttl/tls/00-patch-ns.yaml.j2
- tests/templates/kuttl/upgrade/00-patch-ns.yaml.j2
- tests/test-definition.yaml
Part of stackabletech/issues#566.
OKD:
```
--- PASS: kuttl (437.58s)
--- PASS: kuttl/harness/cluster-operation_kafka-latest-3.6.1_zookeeper-latest-3.9.1_openshift-true (138.06s)
--- PASS: kuttl/harness/logging_kafka-3.6.1_zookeeper-latest-3.9.1_openshift-true (151.34s)
--- PASS: kuttl/harness/delete-rolegroup_kafka-3.6.1_zookeeper-latest-3.9.1_openshift-true (63.12s)
--- PASS: kuttl/harness/smoke_kafka-3.6.1_zookeeper-3.8.3_use-client-tls-true_openshift-true (81.00s)
--- PASS: kuttl/harness/tls_kafka-3.6.1_zookeeper-latest-3.9.1_use-client-tls-true_use-client-auth-tls-true_openshift-true (167.13s)
--- PASS: kuttl/harness/configuration_kafka-latest-3.6.1_zookeeper-latest-3.9.1_openshift-true (29.77s)
--- PASS: …
```
> tests: added namespace patch for openshift tests

- docs/modules/kafka/examples/getting_started/getting_started.sh
This is a leftover from the 24.3 release.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> docs: fix kcat command in the getting started guide

- docs/modules/kafka/examples/getting_started/getting_started.sh
- docs/modules/kafka/examples/getting_started/getting_started.sh.j2
- docs/modules/kafka/examples/getting_started/install-operator-output.txt
- docs/modules/kafka/examples/getting_started/install-operator-output.txt.j2
> docs(getting-started): update stackablectl op install output

- docs/modules/kafka/examples/getting_started/install-operator-output.txt
- docs/modules/kafka/examples/getting_started/install-operator-output.txt.j2
- docs/modules/kafka/examples/getting_started/install_output.txt
- docs/modules/kafka/examples/getting_started/install_output.txt.j2
- docs/modules/kafka/pages/getting_started/installation.adoc
This was leftover from #732 
- Rename `install-operator-output.txt*` to install_output.txt*`
- Replace `Installing` with `Installed`
> docs(getting-started): update stackablectl op install output, and make it consistent with other operator docs

- docs/modules/kafka/pages/usage.adoc
docs: remove home module from refs (stackabletech/documentation#637) / 23.1
> docs: remove home module from refs (stackabletech/documentation#637) / 23.1

- docs/modules/kafka/pages/usage-guide/logging.adoc
- docs/modules/kafka/pages/usage-guide/monitoring.adoc
- docs/modules/kafka/pages/usage-guide/storage-resources.adoc
docs: remove home module from refs (stackabletech/documentation#637) / 23.4
> docs: remove home module from refs (stackabletech/documentation#637) / 23.4

- docs/modules/kafka/pages/usage-guide/logging.adoc
- docs/modules/kafka/pages/usage-guide/monitoring.adoc
- docs/modules/kafka/pages/usage-guide/storage-resources.adoc
docs: remove home module from refs (stackabletech/documentation#637) / 23.7
> docs: remove home module from refs (stackabletech/documentation#637) / 23.7

- docs/modules/kafka/pages/usage-guide/logging.adoc
- docs/modules/kafka/pages/usage-guide/monitoring.adoc
- docs/modules/kafka/pages/usage-guide/storage-resources.adoc
docs: remove home module from refs (stackabletech/documentation#637) / 24.3
> docs: remove home module from refs (stackabletech/documentation#637)

- docs/modules/kafka/pages/usage-guide/storage-resources.adoc
docs: remove home module from refs (stackabletech/documentation#637) / 24.7
> docs: remove home module from refs (stackabletech/documentation#637) / 24.7

- CHANGELOG.md
- deploy/helm/kafka-operator/crds/crds.yaml
- rust/crd/src/authentication.rs
- rust/crd/src/lib.rs
- rust/crd/src/listener.rs
- rust/crd/src/security.rs
- rust/crd/src/tls.rs
- rust/operator-binary/src/discovery.rs
- rust/operator-binary/src/kafka_controller.rs
Reported in https://stackable-workspace.slack.com/archives/C0312UB3LLE/p1722427738668959.
I am using the broker address from the discovery ConfigMap:
```
$ kubectl get -n stackable-products configmaps kafka -o yaml
apiVersion: v1
kind: ConfigMap
data:
KAFKA: kafka.stackable-products.svc.cluster.local:9093
```
The Spark job fails with the following exception:
`javax.net.ssl.SSLHandshakeException: No subject alternative DNS name matching kafka.stackable-products.svc.cluster.local found.`
The certificates of the Kafka brokers contain the following SANs:
```
X509v3 Subject Alternative Name: critical
DNS:kafka-broker-default.stackable-products.svc.cluster.local, DNS:kafka-broker-default-0.kafka-broker-default.stackable-products.svc.cluster.local, DNS:aks-userpool-28268085-
vmss00000p, IP …
```
> fix: Include the bootstrap Kafka service in certificate SANs

- CHANGELOG.md
- docs/modules/kafka/partials/supported-versions.adoc
- tests/test-definition.yaml
Part of https://github.com/stackabletech/issues/issues/626
```[tasklist]
```
> [!IMPORTANT]
> I have left 3.7.1 as LTS as per spreadsheet, and therefore left the `kafka-latest` test dimension and getting_started version as is.
> chore: Add 3.8.0, remove 3.4.1, 3.6.1, 3.6.2

- tests/templates/kuttl/upgrade/04-assert.yaml.j2
Changes `stackable0.0.0-dev` to `stackable24.7.0` in upgrade-zookeeper
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Updating version in upgrade test

- docs/modules/kafka/pages/getting_started/first_steps.adoc
- docs/modules/kafka/pages/getting_started/index.adoc
- docs/modules/kafka/pages/getting_started/installation.adoc
- docs/modules/kafka/pages/index.adoc
- docs/modules/kafka/pages/usage-guide/configuration-environment-overrides.adoc
- docs/modules/kafka/pages/usage-guide/logging.adoc
- docs/modules/kafka/pages/usage-guide/monitoring.adoc
- docs/modules/kafka/pages/usage-guide/security.adoc
- docs/modules/kafka/pages/usage-guide/storage-resources.adoc
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Add descriptions

- tests/templates/kuttl/cluster-operation/20-install-kafka.yaml.j2
- tests/templates/kuttl/cluster-operation/30-stop-kafka.yaml.j2
- tests/templates/kuttl/cluster-operation/40-pause-kafka.yaml.j2
- tests/templates/kuttl/cluster-operation/50-restart-kafka.yaml.j2
- tests/templates/kuttl/configuration/20-install-kafka.yaml.j2
- tests/templates/kuttl/delete-rolegroup/02-install-kafka.yaml.j2
- tests/templates/kuttl/delete-rolegroup/03-delete-secondary.yaml.j2
- tests/templates/kuttl/logging/04-install-kafka.yaml.j2
- tests/templates/kuttl/smoke/30-install-kafka.yaml.j2
- tests/templates/kuttl/tls/20-install-kafka.yaml.j2
- tests/test-definition.yaml
Allow using custom tests like we do in the other operators
> Allow using custom tests

- CHANGELOG.md
- rust/operator-binary/src/kafka_controller.rs
- rust/operator-binary/src/main.rs
Part of: https://github.com/stackabletech/issues/issues/211
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> fix: don't stop the reconciliation if one cluster is invalid

- docs/modules/kafka/examples/getting_started/getting_started.sh
- docs/modules/kafka/examples/getting_started/getting_started.sh.j2
- docs/modules/kafka/examples/getting_started/kafka.yaml
Part of stackabletech/issues#657.
Use server-side to ensure null fields are not overwritten. Port-forward on bootstrap. kcat in place of kafkacat.
N.B. may not need the external-unstable-ip once https://github.com/stackabletech/listener-operator/pull/244 is merged.
> [!NOTE]
> During a Stackable release we need to check (and optionally update) the
> getting-started scripts to ensure they still work after product and operator
> updates.
```shell
pushd $(fd -td getting_started | grep examples); cd code 2>/dev/null || true
kind delete cluster && kind create cluster
./getting_started.sh stackablectl
kind delete cluster && kind create cluster
./getting_started.sh helm
popd
```
> fix(docs): Update getting-started script pre-24.11

- tests/templates/kuttl/tls/30_test_client_auth_tls.sh
- tests/templates/kuttl/tls/30_test_client_tls.sh
- tests/templates/kuttl/tls/31_test-tls-job.yaml.j2
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> test: Use bootstrap listener from discovery ConfigMap in tls test

- docs/modules/kafka/examples/getting_started/kafka.yaml
As we have merged https://github.com/stackabletech/listener-operator/pull/244 there is no need for a special ListenerClass any more
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> doc: Use external-unstable again in getting started guide

- docs/modules/kafka/pages/reference/environment-variables.adoc
Adds missing KUBERNETES_CLUSTER_DOMAIN environment variable to docs
part of stackabletech/issues#668
> Adds missing KUBERNETES_CLUSTER_DOMAIN environment variable to docs

- docs/modules/kafka/examples/getting_started/getting_started.sh
- docs/modules/kafka/examples/getting_started/getting_started.sh.j2
Part of https://github.com/stackabletech/issues/issues/611.
Depends on https://github.com/stackabletech/kafka-operator/pull/790.
> chore(getting_started): Replace templating instructions with make

- CHANGELOG.md
- Cargo.lock
- Cargo.nix
- Cargo.toml
- Makefile
- crate-hashes.json
- docs/modules/kafka/examples/getting_started/getting_started.sh
- docs/modules/kafka/examples/getting_started/getting_started.sh.j2
- rust/operator-binary/src/kafka_controller.rs
Add the following PRs to the release 24.11:
* #790 
* #791 
* #793
> Update release branch

- .github/workflows/build.yml
- CHANGELOG.md
- Cargo.lock
- Cargo.nix
- Cargo.toml
- deploy/helm/kafka-operator/Chart.yaml
- docs/modules/kafka/examples/getting_started/getting_started.sh
- docs/modules/kafka/examples/getting_started/install_output.txt
- docs/templating_vars.yaml
- tests/release.yaml
- tests/templates/kuttl/upgrade/04-assert.yaml.j2
> [!CAUTION]
> ## DO NOT MERGE MANUALLY!
> This branch will be merged (and the commit tagged) by stackable-utils once any necessary commits have been cherry-picked to here from the main branch.
> release: 24.11.1

- CHANGELOG.md
- docs/modules/kafka/pages/reference/discovery.adoc
- rust/operator-binary/src/discovery.rs
See #765
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Deprecate -nodeport discovery ConfigMap

- CHANGELOG.md
- deploy/helm/kafka-operator/crds/crds.yaml
- docs/modules/kafka/pages/usage-guide/overrides.adoc
- docs/modules/kafka/partials/nav.adoc
- rust/crd/src/lib.rs
- rust/operator-binary/src/config/jvm.rs
- rust/operator-binary/src/config/mod.rs
- rust/operator-binary/src/kafka_controller.rs
- rust/operator-binary/src/main.rs
- tests/templates/kuttl/smoke/test_heap.sh
Part of https://github.com/stackabletech/issues/issues/584
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> feat: Support configuring JVM arguments

- Cargo.lock
- examples/logging/simple-kafka-cluster-opa-log4j.yaml
- examples/opa/simple-kafka-cluster-opa-allow-all.yaml
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> docs: Update Rego rules to v1

- tests/test-definition.yaml
We decided not to to with Kafka 3.8.1 for SDP 25.3.0, so this drops back to 3.8.0.
See also: https://github.com/stackabletech/docker-images/pull/1021
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> test: Revert back to 3.8.0

- docs/modules/kafka/examples/getting_started/kafka.yaml
Part of <https://github.com/stackabletech/issues/issues/697>
This PR bumps the following:
- `kafka` to 3.9.0
```shell
kind delete cluster && kind create cluster
./getting_started.sh stackablectl
kind delete cluster && kind create cluster
./getting_started.sh helm
```
> chore(docs): Update getting-started script pre-25.3.0

- CHANGELOG.md
- Cargo.lock
- Cargo.nix
- Cargo.toml
- deploy/helm/kafka-operator/Chart.yaml
- deploy/helm/kafka-operator/crds/crds.yaml
- docs/antora.yml
- docs/modules/kafka/examples/getting_started/getting_started.sh
- docs/modules/kafka/examples/getting_started/install_output.txt
- docs/templating_vars.yaml
- tests/release.yaml
- tests/templates/kuttl/upgrade/04-assert.yaml.j2
> [!CAUTION]
> ## DO NOT MERGE MANUALLY!
> This branch will be merged (and the commit tagged) by stackable-utils once any necessary commits have been cherry-picked to here from the main branch.
> chore: Release 25.3.0

- docs/modules/kafka/examples/getting_started/getting_started.sh
- docs/modules/kafka/examples/getting_started/getting_started.sh.j2
- docs/modules/kafka/pages/getting_started/installation.adoc
- docs/templating_vars.yaml
Part of https://github.com/stackabletech/infrastructure/issues/142
Updating the helm install commands in Getting started sections of the operators was missed during Harbor migration of the docs.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> docs: Update helm install commands

- CHANGELOG.md
- tests/templates/kuttl/logging/01-install-kafka-vector-aggregator.yaml
Part of https://github.com/stackabletech/docker-images/issues/1085.
- Bump to Vector 0.46.1 (chart version 0.42.1) in tests
> test: Bump vector to 0.46.1

- CHANGELOG.md
- Cargo.lock
- Cargo.nix
- Cargo.toml
- crate-hashes.json
- rust/operator-binary/src/crd/authentication.rs
- rust/operator-binary/src/crd/listener.rs
- rust/operator-binary/src/crd/security.rs
- rust/operator-binary/src/discovery.rs
- rust/operator-binary/src/kafka_controller.rs
- rust/operator-binary/src/main.rs
Part of https://github.com/stackabletech/issues/issues/642.
Bump stackable-operator to 0.93.1 which versions common CRD structs.
> chore: Bump stackable_operator to 0.93.1

- CHANGELOG.md
- docs/modules/kafka/pages/reference/discovery.adoc
- rust/operator-binary/src/discovery.rs
- rust/operator-binary/src/kafka_controller.rs
Implementation for https://github.com/stackabletech/kafka-operator/issues/765. Removes the deprecated `-nodeport` discovery ConfigMap (https://github.com/stackabletech/kafka-operator/pull/813). Removes the Note about the `-nodeport` discovery CM from the [Discovery page](https://docs.stackable.tech/home/nightly/kafka/reference/discovery/) of Kafka Operator.
```
--- PASS: kuttl (828.67s)
--- PASS: kuttl/harness/configuration_kafka-latest-3.7.2_zookeeper-latest-3.9.3_openshift-false (31.21s)
--- PASS: kuttl/harness/smoke_kafka-3.9.0_zookeeper-3.9.3_use-client-tls-false_openshift-false (98.06s)
--- PASS: kuttl/harness/cluster-operation_kafka-latest-3.7.2_zookeeper-latest-3.9.3_openshift-false (80.41s)
--- PASS: …
```
> chore: remove -nodeport discovery configmap

- CHANGELOG.md
- Cargo.lock
- Cargo.nix
- Cargo.toml
- crate-hashes.json
- deploy/helm/kafka-operator/crds/crds.yaml
- deploy/helm/kafka-operator/templates/roles.yaml
- rust/operator-binary/src/crd/mod.rs
- rust/operator-binary/src/kafka_controller.rs
- rust/operator-binary/src/main.rs
Part of <https://github.com/stackabletech/issues/issues/725>
> [!NOTE]
> During a Stackable release we need to update various Rust dependencies before
> entering the final release period to ensure we run the latest versions of
> crates. These bumps also include previously updated and released crates from
> the `operator-rs` repository.
> [!NOTE]
> The bumping / updating of Rust dependencies is done in multiple steps:
>
> 1. Update the minimum Version in the root `Cargo.toml` manifest.
> 2. Run the `cargo update` command, which also updates the `Cargo.lock` file.
> 3. Lastly, run `make regenerate-nix` to update the `Cargo.nix` file.
> chore: Bump Rust dependencies pre-25.7.0

- CHANGELOG.md
- deploy/helm/kafka-operator/templates/roles.yaml
Needed since https://github.com/stackabletech/operator-rs/pull/938
Not 100% sure why the product needs this, but it was this way before.
> fix: Add RBAC permission to patch events

- Cargo.lock
- Cargo.nix
- Cargo.toml
- crate-hashes.json
- rust/operator-binary/src/crd/mod.rs
- rust/operator-binary/src/crd/security.rs
- rust/operator-binary/src/kafka_controller.rs
- rust/operator-binary/src/main.rs
Part of https://github.com/stackabletech/issues/issues/762
> chore: Update to stackable-operator 0.95.0

- CHANGELOG.md
- docs/modules/kafka/pages/usage-guide/security.adoc
- docs/modules/kafka/partials/supported-versions.adoc
- examples/logging/simple-kafka-cluster-opa-log4j.yaml
- examples/opa/simple-kafka-cluster-opa-allow-all.yaml
- examples/tls/simple-kafka-cluster-tls.yaml
- rust/operator-binary/src/config/jvm.rs
- rust/operator-binary/src/crd/affinity.rs
- rust/operator-binary/src/crd/listener.rs
- rust/operator-binary/src/crd/mod.rs
- tests/test-definition.yaml
- deprecated in supported versions
- replaced in unittests
- not using as LTS in tests anymore
- added missing changelog entry for https://github.com/stackabletech/kafka-operator/pull/889
> chore: deprecate 3.7.2
